/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LinkMatchInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkPlayerSubmitted"
      | "confidentialProtocolId"
      | "getAllEncryptedScores"
      | "getPlayerByIndex"
      | "getPlayerCount"
      | "getPlayerResult"
      | "hasSubmitted"
      | "playerResults"
      | "players"
      | "submitGameResult"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "GameResultSubmitted" | "LeaderboardUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "checkPlayerSubmitted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllEncryptedScores",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerByIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerResult",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasSubmitted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "playerResults",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "players",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitGameResult",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkPlayerSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllEncryptedScores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "playerResults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "players", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitGameResult",
    data: BytesLike
  ): Result;
}

export namespace GameResultSubmittedEvent {
  export type InputTuple = [player: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [player: string, timestamp: bigint];
  export interface OutputObject {
    player: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeaderboardUpdatedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LinkMatch extends BaseContract {
  connect(runner?: ContractRunner | null): LinkMatch;
  waitForDeployment(): Promise<this>;

  interface: LinkMatchInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkPlayerSubmitted: TypedContractMethod<
    [player: AddressLike],
    [boolean],
    "view"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getAllEncryptedScores: TypedContractMethod<
    [],
    [
      [string[], string[]] & {
        playerAddresses: string[];
        encryptedScores: string[];
      }
    ],
    "view"
  >;

  getPlayerByIndex: TypedContractMethod<
    [index: BigNumberish],
    [string],
    "view"
  >;

  getPlayerCount: TypedContractMethod<[], [bigint], "view">;

  getPlayerResult: TypedContractMethod<[player: AddressLike], [string], "view">;

  hasSubmitted: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  playerResults: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint] & {
        score: string;
        player: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  players: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  submitGameResult: TypedContractMethod<
    [encryptedScore: BytesLike, scoreProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkPlayerSubmitted"
  ): TypedContractMethod<[player: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllEncryptedScores"
  ): TypedContractMethod<
    [],
    [
      [string[], string[]] & {
        playerAddresses: string[];
        encryptedScores: string[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayerByIndex"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getPlayerCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPlayerResult"
  ): TypedContractMethod<[player: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "hasSubmitted"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "playerResults"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint] & {
        score: string;
        player: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "players"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "submitGameResult"
  ): TypedContractMethod<
    [encryptedScore: BytesLike, scoreProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "GameResultSubmitted"
  ): TypedContractEvent<
    GameResultSubmittedEvent.InputTuple,
    GameResultSubmittedEvent.OutputTuple,
    GameResultSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "LeaderboardUpdated"
  ): TypedContractEvent<
    LeaderboardUpdatedEvent.InputTuple,
    LeaderboardUpdatedEvent.OutputTuple,
    LeaderboardUpdatedEvent.OutputObject
  >;

  filters: {
    "GameResultSubmitted(address,uint256)": TypedContractEvent<
      GameResultSubmittedEvent.InputTuple,
      GameResultSubmittedEvent.OutputTuple,
      GameResultSubmittedEvent.OutputObject
    >;
    GameResultSubmitted: TypedContractEvent<
      GameResultSubmittedEvent.InputTuple,
      GameResultSubmittedEvent.OutputTuple,
      GameResultSubmittedEvent.OutputObject
    >;

    "LeaderboardUpdated()": TypedContractEvent<
      LeaderboardUpdatedEvent.InputTuple,
      LeaderboardUpdatedEvent.OutputTuple,
      LeaderboardUpdatedEvent.OutputObject
    >;
    LeaderboardUpdated: TypedContractEvent<
      LeaderboardUpdatedEvent.InputTuple,
      LeaderboardUpdatedEvent.OutputTuple,
      LeaderboardUpdatedEvent.OutputObject
    >;
  };
}
